[pytest]
minversion = 7.0
addopts = -ra -q --disable-warnings --maxfail=1
testpaths = src/qdrant/tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*
[coverage:run]
omit= 
  src/qdrant/create_vector_db.py